apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: njtrdmblv-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:821993d769e68ca58b35e44f440b8814f568cbe3@sha256:0afbc9b6a4ef50be82230e3de2bfafa81dedcb618e4c5c20583ab693314921e4
          name: container-image
